-- AlterTable
ALTER TABLE `Facility` ADD COLUMN `iconColor` VARCHAR(191) NOT NULL DEFAULT '#000000',
    ADD COLUMN `tooltipColor` VARCHAR(191) NOT NULL DEFAULT '#000000';

-- AlterTable
ALTER TABLE `Section` ADD COLUMN `alpha` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `color` VARCHAR(191) NULL,
    ADD COLUMN `strokeAlpha` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `strokeColor` VARCHAR(191) NULL,
    ADD COLUMN `strokeWidth` INTEGER NOT NULL DEFAULT 1;
