-- AlterTable
ALTER TABLE `Facility` MODIFY `iconColor` VARCHAR(191) NULL DEFAULT '#000000',
    MODIFY `tooltipColor` VARCHAR(191) NULL DEFAULT '#000000',
    MODIFY `fontSize` INTEGER NULL DEFAULT 12;

-- AlterTable
ALTER TABLE `Section` MODIFY `alpha` DECIMAL(65, 30) NULL DEFAULT 0.3,
    MODIFY `color` VARCHAR(191) NULL DEFAULT '#FFE699',
    MODIFY `strokeAlpha` DECIMAL(65, 30) NULL DEFAULT 1,
    MODIFY `strokeColor` VARCHAR(191) NULL DEFAULT '#FFE699',
    MODIFY `strokeWidth` INTEGER NULL DEFAULT 1;
